title: KUNDIG
default_lang: en
author:
  name: 'Michael Kündig'
  email: m.kuendig@kuendig.ch
taxonomies:
  - category
  - tag
metadata:
  description: 'My Grav Site'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
logo:
  icon: logo
  text: 'Kundig Sanding'
  url: null
userlinks:
  -
    text: 'Sample link'
    url: '#'
  -
    text: 'Another Sample link'
    url: '#'
header:
  title: 'Kundig Sanding'
  description: 'Some description text...'
  buttons:
    -
      text: 'Some Button'
      url: 'http://tympanus.net/codrops/?p=19439'
      icon: sketch
footer:
  links:
    -
      text: 'Terms &amp; Conditions'
      url: '#'
    -
      text: Legals
      url: '#'
